### ISSUE TITLE
Missing header file in codes/graphSim/math_utils.cpp

### ISSUE THREAD

**Issue by HazardTrigger** [Ideas-Laboratory/Joint_tsne#1]
Missing header files ("assert.h", "math.h") cause some functions to be unavailable and cause errors. I don't know if the bug was caused by system compatibility or negligence, or the author deliberately did it, so I propose to modify the file in question.

**Comment by JoyBoyish** [comment]
The original code in Qt Creator works just fine... So It might be caused by the system. I've already fixed the issue. Thanks a lot!

**Comment by JoyboyWang** [comment]
> 

The original code in Qt Creator works just fine... So It might be caused by the system. I've already fixed the issue. Thanks a lot!
